name: Deploy multi_pro_icon static site

on:
  push:
    branches: [ main ]
    paths:
      - 'multi_pro_icon/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './multi_pro_icon'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
